name: sasat_toko
description: A new Flutter project.
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  base:
    git:
      url: https://github.com/strhmdn14102004/assets.git
      # path: D:/assets
  get: 4.6.6
  dio: 5.3.2
  basic_utils: 5.6.1
  jiffy: 6.3.1
  shared_preferences: 2.2.1
  syncfusion_flutter_datepicker: 27.2.5
  lottie: 3.3.1
  easy_localization: 3.0.7
  pattern_formatter: 4.0.0
  file_picker: 8.1.7
  image_picker: 1.0.6
  smooth_corner: 1.1.1
  collection: 1.19.0
  dotted_border: 2.1.0
  flutter_bloc: 8.1.3
  go_router: 14.2.1
  provider: 6.1.2
  loader_overlay: 2.1.0
  url_launcher: 6.2.4
  package_info_plus: 4.1.0
  webview_flutter: 4.10.0
  shimmer: 3.0.0
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/font/
    - assets/image/
    - assets/lottie/
    - assets/i18n/
  fonts:
    - family: Manrope
      fonts:
        - asset: assets/font/Manrope-Bold.ttf
        - asset: assets/font/Manrope-ExtraBold.ttf
        - asset: assets/font/Manrope-ExtraLight.ttf
        - asset: assets/font/Manrope-Light.ttf
        - asset: assets/font/Manrope-Medium.ttf
        - asset: assets/font/Manrope-Regular.ttf
        - asset: assets/font/Manrope-SemiBold.ttf