// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import "package:firebase_core/firebase_core.dart" show FirebaseOptions;
import "package:flutter/foundation.dart"
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          "DefaultFirebaseOptions have not been configured for windows - "
          "you can reconfigure this by running the FlutterFire CLI again.",
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          "DefaultFirebaseOptions have not been configured for linux - "
          "you can reconfigure this by running the FlutterFire CLI again.",
        );
      default:
        throw UnsupportedError(
          "DefaultFirebaseOptions are not supported for this platform.",
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyAYph65Y8llU5XoKvnWjFqbisTQJpbvpQk",
    appId: "1:140156137344:android:d82aa26dd68d3342351b65",
    messagingSenderId: "140156137344",
    projectId: "satset-toko",
    authDomain: "satset-toko.firebaseapp.com",
    databaseURL: "https://satset-toko-default-rtdb.asia-southeast1.firebasedatabase.app/",
    storageBucket: "gs://satset-toko.appspot.com",
  );

  static const FirebaseOptions android = FirebaseOptions(
     apiKey: "AIzaSyAYph65Y8llU5XoKvnWjFqbisTQJpbvpQk",
    appId: "1:140156137344:android:d82aa26dd68d3342351b65",
    messagingSenderId: "140156137344",
    projectId: "satset-toko",
    authDomain: "satset-toko.firebaseapp.com",
    databaseURL: "https://satset-toko-default-rtdb.asia-southeast1.firebasedatabase.app/",
    storageBucket: "gs://satset-toko.appspot.com",
  );

  static const FirebaseOptions ios = FirebaseOptions(
  apiKey: "AIzaSyAYph65Y8llU5XoKvnWjFqbisTQJpbvpQk",
    appId: "1:140156137344:android:d82aa26dd68d3342351b65",
    messagingSenderId: "140156137344",
    projectId: "satset-toko",
    authDomain: "satset-toko.firebaseapp.com",
    databaseURL: "https://satset-toko-default-rtdb.asia-southeast1.firebasedatabase.app/",
    storageBucket: "gs://satset-toko.appspot.com",
    androidClientId: "230688948865-7jmnmdi3a3c4811d4b3sf1s5klnnhi6n.apps.googleusercontent.com",
    iosBundleId: "com.sisapp.vireo",
  );

  static const FirebaseOptions macos = FirebaseOptions(
     apiKey: "AIzaSyAYph65Y8llU5XoKvnWjFqbisTQJpbvpQk",
    appId: "1:140156137344:android:d82aa26dd68d3342351b65",
    messagingSenderId: "140156137344",
    projectId: "satset-toko",
    authDomain: "satset-toko.firebaseapp.com",
    databaseURL: "https://satset-toko-default-rtdb.asia-southeast1.firebasedatabase.app/",
    storageBucket: "gs://satset-toko.appspot.com",
    androidClientId: "230688948865-7jmnmdi3a3c4811d4b3sf1s5klnnhi6n.apps.googleusercontent.com",
    iosBundleId: "com.sisapp.vireopos.RunnerTests",
  );
}
